### Predict the marks obtained based on the Number of hours studied and the number of hours slept

### 1.Import Pandas for data processing

In [19]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import seaborn as sns
import matplotlib.pyplot as plt
import math

### 2.Read the CSV file

In [3]:
student = pd.read_csv (r'/Users/sabiraliyev/Downloads/02Students.csv')
student.head()

Hours  sHours  Marks
0      0       6     34
1      1       7     36
2      1       6     33
3      1       8     39
4      1       8     42

### 3.Split into X (Independent) and Y (predicted)

In [9]:
X = student[['Hours', 'sHours']]
y = student['Marks'].values.reshape (-1,1)

In [10]:
#view X
X

Hours  sHours
0       0       6
1       1       7
2       1       6
3       1       8
4       1       8
5       2       8
6       2       6
7       3       6
8       3       7
9       3       7
10      3       8
11      4       8
12      4       7
13      4       7
14      5       8
15      5       6
16      6       6
17      6       7
18      7       8
19      7       8
20      7       6
21      7       6
22      8       7
23      8       8
24      9       8
25      9       5
26      9       8
27     10       8
28     10       8
29     11       7

In [11]:
#view Y
y

array([[34],
       [36],
       [33],
       [39],
       [42],
       [45],
       [38],
       [45],
       [53],
       [46],
       [56],
       [59],
       [55],
       [56],
       [72],
       [59],
       [62],
       [71],
       [78],
       [88],
       [61],
       [74],
       [71],
       [89],
       [82],
       [67],
       [89],
       [81],
       [82],
       [79]])

### 4.Split train and test data with 30% test size

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

### 5.Train the Multiple Linear Regression

In [16]:
regressor = LinearRegression()


### 6.Provide the training Data

In [17]:
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### 7.Predict the results

In [18]:
y_pred = regressor.predict(X_test)

In [32]:
compare = pd.DataFrame({'Actual': y_test.flatten(), 'Predict': y_pred.flatten()})
compare

Actual    Predict
0      33  33.832873
1      82  92.411975
2      56  55.278164
3      56  55.805429
4      89  87.182468
5      82  87.182468
6      81  92.411975
7      59  61.034935
8      71  65.737177

### 8.Get the R-Squared

In [24]:
r2 = metrics.r2_score(y_test, y_pred)
r2

0.8840650447993599

### 9.Coefficient and Intercept

In [25]:
regressor.coef_

array([[5.22950655, 5.75677147]])

In [26]:
regressor.intercept_

array([-5.93726277])

In [ ]:
#view mlr_intercept 

### 10.Calculate the errors using RMSE 

In [35]:
mse= metrics.mean_squared_error(y_test, y_pred)
rmse = math.sqrt(mse)

In [36]:
rmse

5.791705019944633